[package]
name = "firefox"
version = "0.1.0"
authors = ["ESukmean <esukmean@esukmean.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0"
tar = "*"
iui = { path = "extern/iui/iui" }
lazy_static = "*"